agent:
  streaming: False
  experiment_location: /Users/scott.mckean/agent_langgraph
  uc_model_name: shm.multimodal.agent_langgraph
model:
  endpoint_name: databricks-meta-llama-3-3-70b-instruct
  parameters:
    temperature: 0
    max_tokens: 400
retriever:
  endpoint_name: one-env-shared-endpoint-3
  index_name: shm.multimodal.multimodal_index
  embedding_model: databricks-gte-large-en
  search_type:
  score_threshold: 0
  parameters:
    k: 3
    query_type: ann
  mapping:
    chunk_text: text
    document_uri: img_path
    primary_key: id
    other_columns:
      - filename
      - type
  chunk_template: 'Passage: {chunk_text}\n Document URI: {document_uri}\n'
